### ISSUE TITLE
.htaccess alternative?

### ISSUE THREAD

**Issue by vanadisv** [josephernest/void#10]
Hello!

I'm trying to set up a simple page for my local network but support for .htaccess is disabled.
Thus, I was wondering how should I edit this so that it works without requiring the .htaccess rewrite rule?

**Comment by josephernest** [comment]
Hi @vanadisv . Are you 100% sure `.htaccess` is disabled? Even for all the little shared hosting I had years ago, it was possible to use it. Simplest solution (I know it's not a real solution...): can't you ask administrator for enabling htaccess / rewrite rule?

It will be possible to provide a solution without `.htaccess`, but you won't have nice URL like:

    www.mywebsite.com/example/about

You will have this instead:

    www.mywebsite.com/example/index.php?page=about

Would this be ok?

**Comment by vanadisv** [comment]
Hi @josephernest, thank you for your quick reply!

I did a quick check using phpinfo and mod_rewrite wasn't listed under the load modules. I'd assume it's either due to security concerns or maybe they just didn't bother to configure everything thoroughly.

As I'd rather not go through the whole administrative/bureaucratic hoops of educational institutes just to ask them to enable rewrite rule, not having a nice URL would be a preferred alternative.

Thus, I'd really appreciate it if you could provide the solution that doesn't require .htaccess.

**Comment by josephernest** [comment]
@vanadisv , a quick hack to do this:

* Replace L21 of `index.php` by:

    $requestedpage = isset($_GET['article']) ? $_GET['article'] : $_GET['page'];

* Replace L67 of `index.php` by:

        echo "<div class=\"article\"><a href=\"?article=". substr($page, 10, strlen($page)-14) . "\">";

* On top of each page (example: `/page/02-about.txt`), add

    URL:index.php?page=about

[Here is a package](http://gget.it/vuoabes3/void-master_without_htaccess.zip), ready-to-use, you only need to unzip it.
Tell me if it works!

**Comment by vanadisv** [comment]
@josephernest, thank you and sorry for the late reply!

I edited the index as you instructed and also tried using the package provided but they don't seem to work. Both of them only displayed the contents of `HIDDEN-404.txt`.

Not sure if this helps but I tried to do some troubleshooting and it seemed like
`$pages`, `$requestedpage`, `$page` are always empty?

Again, I really appreciate your help with this!

PS: The live demo is returning "Not Found".

**Comment by josephernest** [comment]
@vanadisv Oh yes, sorry for the live demo, I don't remember why, but I removed it from the server ;) Here it is again : [live demo](http://5.135.181.77/void-without-htaccess/).

This demo is just the content of [this package](http://gget.it/436cce22/void-master_without_htaccess.zip), unzipped into a directory.
Can you retry to unzip this file into a new directory and browse to it?

___

If it doesn't work, can you download and put [this file](http://gget.it/no1mz7xe/phpinfo.php) on your server, display it from browser, and paste the results somewhere? It would help to debug.

**Comment by vanadisv** [comment]
@josephernest Thank you for the live demo! Seems like everything is working
fine over there.

I actually did unzip the package without htaccess and browsed to it without
changing anything.
However, it is still showing the 404 page.

I have my phpinfo in HTML format over here:
http://paste2.org/C1PbjZwX

I managed to try both the vanilla Void and the Void without htaccess in
another server that mod_rewrite enabled. (Everything else is pretty much
the same as the paste I uploaded).
However, both versions are serving the 404 page again.

**Comment by josephernest** [comment]
Let's meet here: https://tlk.io/void and we'll find a solution together!

**Comment by josephernest** [comment]
This is probably a local configuration problem, as you managed to have "Void_without_htaccess" working on another server. "Void_without_htaccess" doesn't use `mod_rewrite` at all because there is no `.htaccess` in this version.

If you find the reason one day or have more informations @vanadisv, feel free to comment here or reopen this issue. I'll close it for now.

**Comment by vanadisv** [comment]
Hey, @josephernest, sorry for the late reply!
I was occupied throughout the week so I didn't have time to check this.

I think there might be some misunderstandings because I mentioned that I **couldn't** get **either** of them to work.

`void-master & with mod_rewrite -- not working`
`void-master & without mod_rewrite -- not working`
`void-master_without_htaccess & with mod_rewrite -- not working`
`void-master_without_htaccess & without mod_rewrite -- not working`

I also tried to do some investigations and interestingly, adding `AllowOverride All` to the `.htaccess` file on the server with mod_rewrite enabled caused the server to serve up an Internal Server Error page.

Does this suggest that the .htaccess file is indeed being read?

I also checked the directory listing and what I found is even weirder.
````
    etc
     |- apache2
    export
     |- folder1
          |- ...
                       |- My folder
                           |- Void
    home
    ...
    system
    usr
    var
     |- apache2
         |- htdocs
    vol
    ...
````
Seems like my folder is not located in the usual apache folder?

If I had to take a guess I would assume the problem might have something to do with the base url or path perhaps?

Anyhow, I would agree that the problem seems to be on my side so, I guess you can close this issue since there's probably nothing much we could do about it.

I really appreciate your help in this matter so, again, thank you!
