### ISSUE TITLE
Wrong base href when running webserver on Windows

### ISSUE THREAD

**Issue by eBerdnA** [josephernest/void#12]
When running a webserver on Windows ``dirname`` returns "\" instead of "/". This breaks loading the css.

**Comment by josephernest** [comment]
I modified the `index.php` using `DIRECTORY_SEPARATOR` that should be slash or antislash depending on Linux/Windows platform. Does it work now @eBerdnA ?

How should it look like on Windows?

    <base href="\hello\">

or

    <base href="/hello/">

**Comment by josephernest** [comment]
I merged your PR and modified a bit. Can you test the last version @eBerdnA and tell me if it works?
