### ISSUE TITLE
Pages 404

### ISSUE THREAD

**Issue by Valvarexart** [josephernest/void#15]
Not sure what is causing this, but the page links seem to be broken on a default setup (no changes made, php 5.6): http://dysphemia.nfshost.com/

Contact works but about and blog are broken. The text files work if you enter their full address.

**Comment by josephernest** [comment]
Are you sure you are using Apache webserver with .htaccess handling
enabled? (module "rewrite" enabled)?

On Sunday, May 3, 2015, Valvarexart <notifications@github.com> wrote:
> Not sure what is causing this, but the page links seem to be broken on a
default setup (no changes made, php 5.6): http://dysphemia.nfshost.com/
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/VrHQCIial_JQ5FfLLd2HeJJrkveRMDw0ITXeW6aaucLcD8kjzJO-yT7TaAvuWEUq2AlUqrfIsZSofEd0uD4l_LN0_xJ9_iG3a7-LyUtdF8Jgo3jPNX8g12FdzEvxL5eZ0AxZcIWxrkD6vS3yWB7j_aD3_dNVLg=s0-d-e1-ft#https://github.com/notifications/beacon/AF4eExmtMTr1P7BaQNCK6evPs02WvSkqks5oFdqmgaJpZM4EOk4i.gif
>

**Comment by Valvarexart** [comment]
Yes, that should be the case. The funny thing is that it seems to work perfectly fine when using a subdirectory rather than /home/public, ie http://dysphemia.net/void-master/about works great while http://dysphemia.net/about doesn't, with an identical file tree. Sorry if this is something that I've messed up on my end.

**Comment by Valvarexart** [comment]
After messing around a bit with .htaccess everything works fine now.

**Comment by josephernest** [comment]
Great that you solved it by modiying `.htaccess`.

*Sidenote: Exactly the same problem happended once for me, when I moved from a subdirectory to another one and forgot to move the `.htaccess` file!*
