### ISSUE TITLE
only one image per article ?

### ISSUE THREAD

**Issue by b01xy** [josephernest/void#16]
I tried to include several images in an article with 
the usual syntax ![]
and only one image appears, is it normal ?

**Comment by b01xy** [comment]
ok, I could read the code :)

**Comment by josephernest** [comment]
Ok :) is it solved?

If you try something like
~~~
![](url1.jpg)
    
some text

![](url2.jpg)
~~~
it should work

**Comment by b01xy** [comment]
same result here, txt but only one image with code : 
```javascript
![](http://gget.it/1cywgqfg/IMG_5238.JPG)

Profilé de fût de bière étudié en soufflerie
![](http://gget.it/1cywgqfg/IMG_5240.JPG)

Fabrication 3D
![](http://gget.it/1cywgqfg/IMG_5239.JPG)

Gouvernail amovible agile
![](http://gget.it/1cywgqfg/IMG_5241.JPG)
'''

**Comment by josephernest** [comment]
this file exists: http://gget.it/1cywgqfg/IMG_5238.JPG)

but these files don't exist:

http://gget.it/1cywgqfg/IMG_5240.JPG
http://gget.it/1cywgqfg/IMG_5239.JPG
http://gget.it/1cywgqfg/IMG_5241.JPG

because you copied/pasted "1cywgqfg" which is only ok for IMG_5238.JPG

**Comment by b01xy** [comment]
indeed ! :=)
http://gget.it is also a nice web app you know ? ;)
everything works as expected so, thks

**Comment by josephernest** [comment]
Oh I should try it then :)
