### ISSUE TITLE
Remove Title of site from index.php

### ISSUE THREAD

**Issue by nderambure** [josephernest/void#23]
For updating reasons, the only variable that we have to change to configure the website is the site name in index.php. So it should be separated in another file to enable working on void without "personnal data" in files.
So we would have a file called index.php containing the variable and a require witch includes the void.php file (the current index.php content). We would put evverything in a folder (php, css...) but the index.php remain at the root. And the final user will only have to modifiy a smplier file that will not affraid him by the quantity of code :)

**Comment by josephernest** [comment]
The philosophy is : this single-100-lines-of-code-PHP-file is just a *toy* framework, and each person who uses Void can modify the PHP code, add more files according to his tastes, for example to store personal data / variables  in a separate file (as you suggest).

So I would really like to keep the initial goal : 1 single file and < 100 lines of code, to keep the tool simple. Then, everyone (who knows PHP) can modify, add more files to make it more convenient for his usage, etc. It's DIY!

**Comment by nderambure** [comment]
I understand :) But updates are breaking your modifications and site name
is always replaced by the one from the deposit.

2016-01-29 23:24 GMT+01:00 josephernest <notifications@github.com>:

> The philosophy is : this single-100-lines-of-code-PHP-file is just a *toy*
> framework, and each person who uses Void can modify the PHP code, add more
> files according to his tastes, for example to store personal data /
> variables in a separate file (as you suggest).
>
> So I would really like to keep the initial goal : 1 single file and < 100
> lines of code, to keep the tool simple. Then, everyone (who knows PHP) can
> modify, add more files to make it more convenient for his usage, etc. It's
> DIY!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josephernest/void/issues/23#issuecomment-176997181>.
>



-- 
Nicolas Derambure
Gardien de l'entropie.
Développeur Web.
nicolasderambure@gmail.com
http://labomedia.org

**Comment by Andrewpk** [comment]
@josephernest would you be opposed to checking an ENV var and requiring that path if it exists?
