### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by cfjedimaster** [josephernest/void#3]
Unless I'm missing it - are there docs anywhere?

**Comment by josephernest** [comment]
Not yet ;)
The closest thing to a doc is this: http://www.thisisvoid.org/article/02-howto

**Comment by josephernest** [comment]
@cfjedimaster Here is the beginning of a doc: http://thisisvoid.org/howtoinstall

Do you have some ideas of improvements?

**Comment by cfjedimaster** [comment]
I'm still confused as to how you "run" this. You describe the format for
blog posts, but how do I go from that to a static output?

On Sat, Apr 11, 2015 at 5:33 PM, josephernest <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> Here is the beginning of
> a doc: http://thisisvoid.org/howtoinstall
>
> Do you have some ideas of improvements?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josephernest/void/issues/3#issuecomment-91935930>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by josephernest** [comment]
@cfjedimaster It's PHP. So the only thing you need is:

* A running Apache webserver + PHP 
* Unzip the [Void package](http://github.com/josephernest/void/archive/master.zip) in Apache's `www` folder  (usually `/var/www` by default?)

Browse your website, you'll see the output.

Is it this information you were looking for @cfjedimaster  or something else?

You can access it directly via browser.

**Comment by cfjedimaster** [comment]
I guess I was expecting something like Jeckle. (And yeah, I know I spelled
that wrong.) A dynamic server while you write content, and then the ability
to spit out a folder of static HTML resources. Know what I mean?

On Mon, Apr 13, 2015 at 3:43 PM, josephernest <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> It's PHP. So the only
> thing you need is:
>
>    - A running Apache webserver + PHP
>    - Unzip the Void package
>    <https://github.com/josephernest/void/archive/master.zip> in Apache's
>    www folder (usually /var/www by default?)
>
> Browse your website, you'll see the output.
>
> Is it this information you were looking for @cfjedimaster
> <https://github.com/cfjedimaster> or something else?
>
> You can access it directly via browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josephernest/void/issues/3#issuecomment-92492789>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by josephernest** [comment]
Oh ok @cfjedimaster . You seem to want a "static HTML generator" like Jekyll.
i.e. once your articles / pages are written, you want to be able to export all the stuff into HTML in a folder? Is it right?

There are hundreds of tools that do this (Jekyll is the most famous), but here **Void** has a different concept:

* you just have to drop the pages in `/page/mypage.txt` or articles in `/article/04-newarticle.txt`
* they will be generated / served in real-time by PHP

You don't have to worry about exporting to a folder, PHP will serve in realtime.
If your concern is performance (you seem to want static HTML), here it's quite fast, even if it's not really static: http://www.thisisvoid.org/article/05-perf

The concept here is a bit *in the middle* of 

* a "standard CMS" (but without all the weight!)  
* and a static generator (but without having to regenerate all the static HTML folder after each modification).

**Comment by cfjedimaster** [comment]
Ok, thank you! Can I suggest this be "digested" a bit and put up in the
docs to make it more clear. :)

On Mon, Apr 13, 2015 at 4:34 PM, josephernest <notifications@github.com>
wrote:

> Oh ok @cfjedimaster <https://github.com/cfjedimaster> . You seem to want
> a "static HTML generator" like Jekyll.
> i.e. once your articles / pages are written, you want to be able to export
> all the stuff into HTML in a folder? Is it right?
>
> There are hundreds of tools that do this (Jekyll is the most famous), but
> here *Void* has a different concept:
>
>    - you just have to drop the pages in /page/mypage.txt or articles in
>    /article/04-newarticle.txt
>    - they will be generated / served in real-time by PHP
>
> You don't have to worry about exporting to a folder, PHP will serve in
> realtime.
> If your concern is performance (you seem to want static HTML), here it's
> quite fast, even if it's not really static:
> http://www.thisisvoid.org/article/05-perf
>
> The concept here is a bit *in the middle* of
>
>    - a "standard CMS" (but without all the weight!)
>     - and a static generator (but without having to regenerate all the
>    static HTML folder after each modification).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josephernest/void/issues/3#issuecomment-92507786>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by josephernest** [comment]
Sure! The doc is currently on progress (when I posted Void three days ago, it was just a prototype with no doc)...

Do you think this fits your requirements : non-static (content is generated in realtime by PHP, so no worry about reexporting HTMLs to a folde) +  still, the pages are written in text editor or command-line . Or you want something else?

Having your feedback on this might help me to understand the needs.

**Comment by cfjedimaster** [comment]
I hope this doesn't upset you - but I don't really have any "needs". I
spend a lot of time looking at static site generators in general, it's a
passion of mine (something I've written about, presented about, etc), so I
check out stuff like this just to learn.

On Mon, Apr 13, 2015 at 4:40 PM, josephernest <notifications@github.com>
wrote:

> Sure! The doc is currently on progress (when I posted Void three days ago,
> it was just a prototype with no doc)...
>
> Do you think this fits your requirements : non-static (content is
> generated in realtime by PHP, so no worry about reexporting HTMLs to a
> folde) + still, the pages are written in text editor or command-line . Or
> you want something else?
>
> Having your feedback on this might help me to understand the needs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josephernest/void/issues/3#issuecomment-92509284>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by josephernest** [comment]
I understand easily, I also have similar kind of passions :)
