### ISSUE TITLE
 Fatal error: Can't use function return value in write context in /home/public/void/index.php on line 33

### ISSUE THREAD

**Issue by Valvarexart** [josephernest/void#5]
I get the error in the title after uploading the contents (I have tried both git cloning and unzipping the suggested zip file) to my server. I've set permissions on folders to 755 and files to 644 - should I do anything else?

Thanks

**Comment by dragonrider23** [comment]
That's because the empty() on line 35 is taking a function return as it's value. What PHP version are you running?

**Comment by Valvarexart** [comment]
5.5.23

**Comment by dragonrider23** [comment]
PHP 5.5 shouldn't be a problem for empty(). I put in a pull request that should fix it either way.

**Comment by josephernest** [comment]
@Valvarexart does it work if you replace Line 33 by:

     <title><?php echo (trim($pagetitle) ? "$sitename - $pagetitle" : "$sitename"); ?></title>

**Comment by Settler6079SW** [comment]
Same problem here. PHP 5.4.39-0
I do not know anything about PHP, but i removed the trim() function. I know this is not a solution, but it has temporarily solved the problem until a solution.

**Comment by dragonrider23** [comment]
In PHP 5.4, the empty() construct can not take a function return as it's input. By removing trim, you're removing the function return problem.

**Comment by josephernest** [comment]
@Settler6079SW can you try the latest version of `index.php` I just have updated?
Does it work for you?

**Comment by Settler6079SW** [comment]
@josephernest it works well, thank you for the update

**Comment by josephernest** [comment]
Ok then I'll close the issue. If the new update of `index.php` @Valvarexart , feel free to reopen.
