### ISSUE TITLE
Subdirectories

### ISSUE THREAD

**Issue by sysadminwatdo** [josephernest/void#8]

**Comment by josephernest** [comment]
What do you mean by "subdirectories" @sysadminwatdo ?

**Comment by sysadminwatdo** [comment]
I commented too quickly - resolved with a fix to apache config, it was
ignoring .htaccess.  My issue, not a code issue.

Best,
Daniel
(765)444-9545
sysadmin@watdo.org or public@zardwiz.com

**Comment by josephernest** [comment]
Ok thanks. So i'll close the issue now.
