### ISSUE TITLE
Syntax error, unexpected T_OBJECT_OPERATOR on line 59

### ISSUE THREAD

**Issue by nnorthway** [josephernest/void#9]
'Expecting ',' or ':' in .../index.php'
Tried entering both on the line before to no avail...thought the syntax looked correct, anyways.

**Comment by josephernest** [comment]
Are you sure you are using PHP5? Try to create a `.htaccess` file at the root of your website (or open the `.htaccess` in Void) and add:

    SetEnv PHP_VER 5
    AddType x-mapp-php5 .php

Does it work?

**Comment by nnorthway** [comment]
Yeah, just updated the server not too long ago.

**Comment by josephernest** [comment]
Can you run this file on your server, and paste the results somewhere? http://gget.it/no1mz7xe/phpinfo.php
It would help to debug. Thanks in advance @nnorthway

**Comment by nnorthway** [comment]
Hey, Joseph. I just rechecked and tried to verify I was using PHP 5 and to
my bewilderment, I was using PHP 3. I'm sorry for the confusion. It's been
updated and is working now. I manage multiple websites and must have gotten
them confused. It looks beautiful now, though! Thanks a lot.

On Sun, Apr 12, 2015 at 10:56 AM, Nate Northway <northwayn@gmail.com> wrote:

> Yeah, just updated the server not too long ago.
> On Apr 12, 2015 8:39 AM, "josephernest" <notifications@github.com> wrote:
>
>> Are you sure you are using PHP5? Try to create a .htaccess file at the
>> root of your website (or open the .htaccess in Void) and add:
>>
>> SetEnv PHP_VER 5
>> AddType x-mapp-php5 .php
>>
>> Does it work?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/josephernest/void/issues/9#issuecomment-92062379>.
>>
>


-- 
Take Care!
-Nate Northway

**Comment by josephernest** [comment]
Great that the issue is solved :) Thanks
